---
title: "Yükseköğretimde Puanların Ötesinde Etkin Raporlama"
subtitle: "Verilerle Oynuyorum"
author: "Doc.Dr. Kubra Atalay Kabasakal"
output:
  html_document:
    css: slides-style.css
    theme: cerulean
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
    code-fold: true
    code-link: true
    code-tools: true
---

## Aritmetik ortalama

bir veri kümesindeki tüm değerlerin toplamının değer sayısına bölünmesini temsil eden bir merkezi eğilim ölçüsüdür. Genellikle veri kümesinin merkezini veya tipik değerini temsil eden tek bir değer sağlayarak bir veri kümesini özetlemek için kullanılır.

$$
\text{Ortalama} = \frac{x_1 + x_2 + \cdots + x_n}{n} = \frac{\sum_{i=1}^{n} x_i}{n}
$$

### Özellikleri

-   Tüm değerleri toplayıp değer sayısına bölerek hesaplamak kolaydır.

-   Aritmetik ortalama, veri kümesindeki her değeri dikkate alır ve bu da onu kapsamlı bir ölçü haline getirir.

-   Başlıca dezavantajlarından biri, sonucu çarpıtabilecek aykırı değerlerden (aşırı yüksek veya düşük değerler) büyük ölçüde etkilenebilmesidir.

-   Aritmetik ortalama, bir aralık veya oran ölçeğinde ölçülen veriler için uygundur (sayıların aralarında anlamlı mesafeler olduğu ve gerçek bir sıfırın bulunduğu durumlarda).

-   Simetrik bir dağılımda ortalama merkezdedir ve dağılımın denge noktası olarak düşünülebilir.

-   Belirli bir veri kümesi için yalnızca bir aritmetik ortalama vardır, bu da onu benzersiz bir merkezi eğilim ölçüsü haline getirir.

-   Veri noktalarının ortalamadan sapmalarının toplamı her zaman sıfırdır, yani,

$$
\sum_{i=1}^{n} (x_i - \tilde{x}) = 0
$$

Aritmetik ortalama genellikle varyans ve standart sapma gibi diğer istatistiksel hesaplamalarda kullanılır.

| Sayı | Ortalama | Fark |
|------------------------|------------------------|------------------------|
| 3 | 6 | -3 |
| 6 | 6 | 0 |
| 7 | 6 | 1 |
| 8 | 6 | 2 |
| $$\sum_{i=1}^{n} x_i = 24$$ |  | $$\sum_{i=1}^{n} x_i - \tilde{x} = 0$$ |

## Standart Sapma

Bir veri kümesindeki dağılım miktarının bir ölçüsüdür. Bireysel veri noktalarının veri kümesinin ortalamasından ne kadar saptığını gösterir. Daha küçük bir standart sapma, veri noktalarının ortalamaya daha yakın olduğu anlamına gelirken, daha büyük bir standart sapma daha fazla yayılma olduğunu gösterir.

Evren için:

$$
\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2}
$$

Örneklem için:

$$
s = \sqrt{\frac{1}{n-1} \sum_{i=1}^{n} (x_i - \bar{x})^2}
$$

## Standart Sapmanın Özellikleri

-   Veri noktalarının ortalamaya göre yayılımını ölçer. Daha yüksek bir standart sapma, verilerde daha fazla değişkenlik olduğu anlamına gelir.

-   Standart sapma orijinal verilerle aynı birimlere sahiptir, bu da bağlam içinde yorumlanmasını kolaylaştırır.

-   Ortalama gibi, standart sapma da uç değerlerden etkilenir, çünkü aykırı değerler yayılımı artırabilir.

-   Standart sapma, karesel sapmalara dayandığı için her zaman pozitiftir.

-   Aralık veya oran ölçeklerinde ölçülen veriler için uygundur.

-   Standart sapma, varyansın kareköküdür ve dağılımın bir başka ölçüsüdür.

-   İstatistik, finans ve diğer alanlarda veri değişkenliğini analiz etmek ve güven aralıkları oluşturmak için yaygın olarak kullanılır.

### Yorum

-   Düşük standart sapma veri noktalarının ortalamaya yakın olduğunu gösterir.

-   Yüksek standart sapma veri noktalarının daha geniş bir değer aralığına yayıldığını gösterir.

## Simülasyon Araçları

-   [**Normal Dağılım Simülasyonu1:** ](https://buluttevfik.shinyapps.io/normdv2/)

-   [**Normal Dağılım Simülasyonu2:**](https://www.statcrunch.com/applets/type2&normal)

-   [**Ortalama ve Ortanca**](https://www.statcrunch.com/applets/type1&meanmedian)

-   [**Betimsel Istatistikler**](https://phet.colorado.edu/sims/html/center-and-variability/latest/center-and-variability_all.html)

- [app1](https://rkkatalay.shinyapps.io/4005_VM_app1/)

- [app2](https://rkkatalay.shinyapps.io/4005_VM_app2/)

- [eski sunu](https://atalay-k.github.io/2237_SP)

